name: UML to PNG Converter
on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - run: echo "Conversion automatique du .du en .png ..."

    - name: Run plantuml on all .du files
      run: for filename in ./conception/*.du; do java -jar ./conception/plantuml.jar "$filename"; done;
    
    # - run: echo "Succ√®s ! Graphes UML disponibles:"

    # - name: List converted files
    #   run: ls -1 | grep .png$
